apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
  labels:
    app: auth
    app.kubernetes.io/name: carenest
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: {{ .Values.ports.auth }}
      targetPort: {{ .Values.ports.auth }}
      name: http
