apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service
  namespace: {{ .Values.namespace }}
  labels:
    app: pharmacy
    app.kubernetes.io/name: carenest
spec:
  type: ClusterIP
  selector:
    app: pharmacy
  ports:
    - port: {{ .Values.ports.pharmacy }}
      targetPort: {{ .Values.ports.pharmacy }}
      name: http
