apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    app.kubernetes.io/name: carenest
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: {{ .Values.ports.redis }}
      targetPort: {{ .Values.ports.redis }}
      name: redis
