apiVersion: v1
kind: Secret
metadata:
  name: carenest-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: carenest
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MONGO_URI_AUTH: {{ printf "mongodb://mongo-service:%s/carenest_auth" (.Values.ports.mongo | toString) | b64enc | quote }}
  MONGO_URI_APPOINTMENT: {{ printf "mongodb://mongo-service:%s/carenest_appointments" (.Values.ports.mongo | toString) | b64enc | quote }}
  MONGO_URI_PHARMACY: {{ printf "mongodb://mongo-service:%s/carenest_pharmacy" (.Values.ports.mongo | toString) | b64enc | quote }}
  MONGO_URI_NOTIFY: {{ printf "mongodb://mongo-service:%s/carenest_notifications" (.Values.ports.mongo | toString) | b64enc | quote }}
